argo-cd:
  admin:
    enabled: true
  exec:
    enabled: true
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure